

function g.fastStart()
  
  Scene.runScene(Scene.overMap_scene)
  
  p = Player.new()
  p.calendar:setDate(1,1,1,5) --517年1月1日8点
  
  --cmap = MapFactory.createFromTemplateId("Vernis")
  wmap = MapFactory.createOverMapFromTemplateId("tyris1")
  cmap = MapFactory.getOrCreateIdmap("Vernis")
  --大地图位置
  p:setPosition(26,31)
  
  local mc = UnitFactory.createMC("Nilo","wizard")
  p.mc = mc
  p.team[1] = mc
  cmap:unitSpawn(mc,38,20,true)
  
  
  local girl = UnitFactory.createMC("teenage_girl","warrior")
  p.team[2] = girl
  cmap:unitSpawn(girl,35,20,true)
  p.inv:addItem(ItemFactory.create("katana"))
  p.inv:addItem(ItemFactory.create("shield_light"))
  p.inv:addItem(ItemFactory.create("shield_heavy"))
  p.inv:addItem(ItemFactory.create("dagger"))
  p.inv:addItem(ItemFactory.create("dagger"))
  p.inv:addItem(ItemFactory.create("long_sword"))
  p.inv:addItem(ItemFactory.create("sledgehammer"))
  p.inv:addItem(ItemFactory.create("scythe"))
  p.inv:addItem(ItemFactory.create("mace"))
  p.inv:addItem(ItemFactory.create("huge_sword"))
  p.inv:addItem(ItemFactory.create("wakizashi"))
  p.inv:addItem(ItemFactory.create("claymore"))
  local item = ItemFactory.create("saving_pot")
  p.inv:addItem(item)
  item = ItemFactory.create("pistol")
  p.inv:addItem(item)
  p.inv:addItem(ItemFactory.create("pistol"))
  item = ItemFactory.create("machine_gun")
  p.inv:addItem(item)
  item = ItemFactory.create("repeating_bow")
  p.inv:addItem(item)
  item = ItemFactory.create("revolver")
  p.inv:addItem(item)
  item = ItemFactory.create("laser_gun")
  p.inv:addItem(item)
  item = ItemFactory.create("shotgun")
  p.inv:addItem(item)
  item = ItemFactory.create("heavy_mg")
  p.inv:addItem(item)
  item = ItemFactory.create("sniper_rifle")
  p.inv:addItem(item)
  
  item = ItemFactory.create("spear")
  p.inv:addItem(item)
  item = ItemFactory.create("noble_coat")
  p.inv:addItem(item)
  item = ItemFactory.create("protection_coat")
  p.inv:addItem(item)
  item = ItemFactory.create("shield_arm")
  p.inv:addItem(item)
  item = ItemFactory.create("bejeweled_necklace")
  p.inv:addItem(item)
  item = ItemFactory.create("magic_gloves")
  p.inv:addItem(item)
  item = ItemFactory.create("long_sword")
  p.inv:addItem(item)
  item = ItemFactory.create("beer_shelf")
  p.inv:addItem(item)
  item = ItemFactory.create("scarecrow1")
  p.inv:addItem(item)
  item = ItemFactory.create("kotatsu")
  p.inv:addItem(item)
  item = ItemFactory.create("bear_fur")
  p.inv:addItem(item)
  item = ItemFactory.create("toy_bear")
  p.inv:addItem(item)
  item = ItemFactory.create("goods1")
  item:set_num(10)
  p.inv:addItem(item)
  item = ItemFactory.create("goods2")
  p.inv:addItem(item)
  item = ItemFactory.create("empty_tub")
  p.inv:addItem(item)
  item = ItemFactory.create("potting1")
  p.inv:addItem(item)
  item = ItemFactory.create("short_bow")
  p.inv:addItem(item)
  item = ItemFactory.create("potting3")
  p.inv:addItem(item)
  item = ItemFactory.create("potting4")
  p.inv:addItem(item)
  item = ItemFactory.create("potting5")
  p.inv:addItem(item)
  item = ItemFactory.create("potting6")
  p.inv:addItem(item)
  item = ItemFactory.create("potting7")
  p.inv:addItem(item)
  item = ItemFactory.create("potting8")
  p.inv:addItem(item)
  item = ItemFactory.create("potting9")
  p.inv:addItem(item)
  item = ItemFactory.create("potting10")
  p.inv:addItem(item)
  item = ItemFactory.create("potting11")
  p.inv:addItem(item)
  item = ItemFactory.create("potting12")
  p.inv:addItem(item)
  item = ItemFactory.create("potting13")
  p.inv:addItem(item)
  item = ItemFactory.create("potting14")
  p.inv:addItem(item)
  item = ItemFactory.create("pickax")
  p.inv:addItem(item)
  item = ItemFactory.create("alchemy_tools")
  p.inv:addItem(item)
  item = ItemFactory.create("saucepot")
  p.inv:addItem(item)
  
  
  
  g.initCamera()
  g.camera:updateRect(cmap)
  g.camera:setCenter(38*64,20*64)
  g.wcamera:updateRect(wmap)
  g.wcamera:setCenter(38*64,20*64)
  
  
  
  p.mc:learnAbility("fire_ball")
  p.mc:learnAbility("jump_slash")
  p.mc:learnAbility("round_slash")
  p.mc:learnAbility("ancient_wisdom")
  
  girl:learnAbility("charge")
  girl:learnAbility("jump_slash")
  girl:learnAbility("round_slash")
  girl:learnAbility("burst_punch")
end