return { main = {saveIndex = 1 },
{
	delayRL_list = {
	},
	max_hp = 11,
	class_id = "wizard",
	sex_male = true,
	weapon_list = {
		range = {
		},
		melee = {
			[1] = {
				unarmed = true,
				isMelee = true,
			},
		},
		MGR = 0,
		use_shield = false,
		DEF = 0,
		totalWeight = 0,
	},
	hp_regen = 0.44928,
	mp = 29,
	_x = 21,
	abilities = {
		[1] = {saveIndex = 2 },
		[2] = {saveIndex = 3 },
		[3] = {saveIndex = 4 },
		[4] = {saveIndex = 5 },
	},
	_y = 14,
	inv = {saveIndex = 6 },
	delayAnim_list = {
	},
	bonus = {saveIndex = 7 },
	clips = {
	},
	id = "Nilo",
	hp = 11,
	equipment = {
	},
	mp_regen = 0.924,
	max_mp = 29,
	damage_queue = {
	},
	anim_id = "Nilo",
	attr = {
		mana = 110,
		ler_p = 1.3,
		life = 100,
		chr = 4.8,
		ler = 10.8,
		speed = 70,
		mag = 20.4,
		wil = 18,
		per = 10.8,
		str = 4.8,
		per_p = 1.3,
		chr_p = 0.8,
		con_p = 0.9,
		mag_p = 2.1,
		str_p = 0.8,
		exp_point = 87,
		dex_p = 1.2,
		wil_p = 1.9,
		con = 6,
		dex = 9.6,
	},
	frames = {
	},
	anim = {dataFormName = "unitAnim", id = "Nilo" },
	faction = 1,
	brain = {saveIndex = 8 },
	skill = {
		tailoring = 1,
		alchemy = 4.8,
		firearm = 1,
		cutting = 1,
		bow = 1,
		throw = 1,
		cooking = 1,
		mechanics = 1,
		bashing = 1,
		soft_weapon = 1,
		fabrication = 1,
		energy_gun = 1,
		big_gun = 1,
		stabbing = 1,
		gardening = 1,
		fishing = 1,
		blacksmithing = 1,
		polearm = 4.8,
		performer = 1,
		magic_chant = 4.8,
		jeweler = 1,
		martial_arts = 1,
		shield = 1,
	},
	class = {dataFormName = "class", id = "wizard" },
	traits = {
		[1] = {saveIndex = 9 },
	},
	basis = {saveIndex = 10 },
	saveType = "Unit",
	effects = {
	},
	type = {dataFormName = "unit", id = "Nilo" },
	status = {
		scaleX = 1,
		rate = 0,
		rot = 0,
		dz = 0,
		camera_dy = 0,
		scaleY = 1,
		dx = 0,
		camera_dx = 0,
		face = 8,
		dy = 0,
	},
	actionBar = {saveIndex = 11 },
	abilities_level = {
	},
},
{
	type = {dataFormName = "ability", id = "fire_ball" },
	saveType = "Ability",
	id = "fire_ball",
},
{
	type = {dataFormName = "ability", id = "jump_slash" },
	saveType = "Ability",
	id = "jump_slash",
},
{
	type = {dataFormName = "ability", id = "round_slash" },
	saveType = "Ability",
	id = "round_slash",
},
{
	type = {dataFormName = "ability", id = "ancient_wisdom" },
	saveType = "Ability",
	id = "ancient_wisdom",
},
{
	maxNum = 300,
	weight = 0,
	list = {
	},
	saveType = "Inventory",
	weight_dirty = false,
	unsorted = false,
	maxWeight = 100000,
	ground = true,
},
{
	saveType = "Bonus",
},
{
	owner = {saveIndex = 1 },
	saveType = "Brain",
	thisPlan = 749,
},
{
	type = {dataFormName = "trait", id = "magicRes" },
	saveType = "Trait",
	id = "magicRes",
},
{
	mana = 110,
	ler_p = 1.3,
	life = 100,
	chr = 4,
	ler = 10,
	speed = 70,
	mag = 20,
	wil = 18,
	str_p = 0.8,
	per = 10,
	str = 4,
	MGR = 10,
	per_p = 1.3,
	DEF = 0,
	chr_p = 0.8,
	con_p = 0.9,
	mag_p = 2.1,
	saveType = "Bonus",
	exp_point = 87,
	dex_p = 1.2,
	wil_p = 1.9,
	con = 6,
	dex = 9,
},
{
	[1] = {
		state = "normal",
		etype = "ability",
		val = {saveIndex = 2 },
	},
	[2] = {
		state = "normal",
		etype = "ability",
		val = {saveIndex = 3 },
	},
	[3] = {
		state = "normal",
		etype = "ability",
		val = {saveIndex = 4 },
	},
	[4] = {
		state = "normal",
		etype = "ability",
		val = {saveIndex = 5 },
	},
	saveType = "ActionBar",
},
}